spring.application.name=jtechstore

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=JTechStore;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.thymeleaf.cache=false

spring.web.resources.cache.period=365d
spring.web.resources.chain.cache=true

server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size=1024